//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDataStructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZDataStructure.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to copy the value elements of a SkipList to an array that is too small..
        /// </summary>
        internal static string BadArrayCopyTo {
            get {
                return ResourceManager.GetString("BadArrayCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to access a SkipListEnumerator that is positioned before the first element of a SkipList or after the last element..
        /// </summary>
        internal static string BadEnumAccess {
            get {
                return ResourceManager.GetString("BadEnumAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass an out of range index to the CopyTo method of a SkipList..
        /// </summary>
        internal static string BadIndexCopyTo {
            get {
                return ResourceManager.GetString("BadIndexCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SkipList was set to use the IComparable interface and an attempt was made to add a key that does not support this interface..
        /// </summary>
        internal static string ComparableError {
            get {
                return ResourceManager.GetString("ComparableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkipListEnumerator is no longer valid. The SkipList has been modified since the creation of this enumerator..
        /// </summary>
        internal static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to add an element in which the key of the element already exists in the SkipList..
        /// </summary>
        internal static string KeyExistsAdd {
            get {
                return ResourceManager.GetString("KeyExistsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass a null array to the CopyTo method of a SkipList..
        /// </summary>
        internal static string NullArrayCopyTo {
            get {
                return ResourceManager.GetString("NullArrayCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to pass a null key to a SkipList..
        /// </summary>
        internal static string NullKey {
            get {
                return ResourceManager.GetString("NullKey", resourceCulture);
            }
        }
    }
}
